[package]
name = "bevy-dev-template"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.16"
bevy_egui = { version = "0.34.0", default-features = false }
bevy-inspector-egui = "0.31"
